In [1]:
###Libraries

In [2]:
import numpy as np
import pandas as pd
import nltk

In [3]:
###Read csv

In [4]:
data = pd.read_csv('sample1.csv')
text_data = data[['issue_title','issue_body']]
print(text_data)

                                             issue_title  \
0      __tileSrcRect is null in Entities.ldtk Sample ...
1                   Update the blog link in the SEF Site
2      🐛 Parser cannot properly distinguish between p...
3      "Row added" snackbar is not visible if the gri...
4      [CRASH]  _tcp_write_on_socket crashes when flu...
...                                                  ...
72284  [HELP] Volume Mount hostpath: Unable to mount ...
72285        is form.progress valid for upload progress?
72286  RPi used for door contact sensors, warning in log
72287  Tail latency of envoy proxy is bad if every re...
72288  Setting the date value programmatically  after...

                                              issue_body
0      In the Entities example, we there are some `__...
1      **Describe the bug**\r\nUpdate the blog link i...
2      Consider these two expressions:\r\n```\r\nf (g...
3      ## Description  \r\nWhen grid has no height an...
4      <!--\r\nThank you for reporting a crash in Ope...
...                                                  ...
72284  hi Team I am facing the below issue. Any solut...
72285  I thought form.progress would get fired every ...
72286  Thank you for the most excellent plug-in!! \r\...
72287  We have envoy running as the front door servic...
72288  Hi,  Im using this Datepair, but i'm strugglin...

[72289 rows x 2 columns]

In [5]:
###Noise reduction

In [6]:
import string
string.punctuation

text_data.loc[:,'issue_title'] = text_data['issue_title'].str.lower()
text_data.loc[:,'issue_body'] = text_data['issue_body'].str.lower()

def remove_punctuation(text):
    if not isinstance(text, str):
        text = ""
    punctuationFree = "".join([i for i in text if i not in string.punctuation])
    return punctuationFree

text_data.loc[:,'issue_title'] = text_data['issue_title'].apply(lambda x:remove_punctuation(x))
text_data.loc[:,'issue_body'] = text_data['issue_body'].apply(lambda x:remove_punctuation(x))
text_data.head()

,issue_title,issue_body
0,tilesrcrect is null in entitiesldtk sample but...,in the entities example we there are some tile...
1,update the blog link in the sef site,describe the bug\r\nupdate the blog link in th...
2,🐛 parser cannot properly distinguish between p...,consider these two expressions\r\n\r\nf g x\r\...
3,row added snackbar is not visible if the grid ...,description \r\nwhen grid has no height and ...
4,crash tcpwriteonsocket crashes when flushing ...,\r\nthank you for reporting a crash in opensip...

In [7]:
###Tokenization

In [8]:
#nltk.download('punkt')

def tokenization(text):
    tokens = nltk.word_tokenize(text)
    repr(tokens)
    return tokens

text_data.loc[:,'token_title'] = text_data['issue_title'].apply(lambda x: tokenization(x))
text_data.loc[:,'token_body'] = text_data['issue_body'].apply(lambda x: tokenization(x))
text_data.head()

C:\Users\imerp\AppData\Local\Temp\ipykernel_21688\3338922036.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text_data.loc[:,'token_title'] = text_data['issue_title'].apply(lambda x: tokenization(x))
C:\Users\imerp\AppData\Local\Temp\ipykernel_21688\3338922036.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text_data.loc[:,'token_body'] = text_data['issue_body'].apply(lambda x: tokenization(x))

,issue_title,issue_body,token_title,token_body
0,tilesrcrect is null in entitiesldtk sample but...,in the entities example we there are some tile...,"[tilesrcrect, is, null, in, entitiesldtk, samp...","[in, the, entities, example, we, there, are, s..."
1,update the blog link in the sef site,describe the bug\r\nupdate the blog link in th...,"[update, the, blog, link, in, the, sef, site]","[describe, the, bug, update, the, blog, link, ..."
2,🐛 parser cannot properly distinguish between p...,consider these two expressions\r\n\r\nf g x\r\...,"[🐛, parser, can, not, properly, distinguish, b...","[consider, these, two, expressions, f, g, x, f..."
3,row added snackbar is not visible if the grid ...,description \r\nwhen grid has no height and ...,"[row, added, snackbar, is, not, visible, if, t...","[description, when, grid, has, no, height, and..."
4,crash tcpwriteonsocket crashes when flushing ...,\r\nthank you for reporting a crash in opensip...,"[crash, tcpwriteonsocket, crashes, when, flush...","[thank, you, for, reporting, a, crash, in, ope..."

In [9]:
###Stop word removal

In [10]:
#nltk.download('stopwords')
from nltk.corpus import stopwords
def remove_stop_words(text):
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in text if word not in stop_words]
    return tokens

text_data.loc[:,'token_title'] = text_data['token_title'].apply(lambda x:remove_stop_words(x))
text_data.loc[:,'token_body'] = text_data['token_body'].apply(lambda x:remove_stop_words(x))
text_data.head()

,issue_title,issue_body,token_title,token_body
0,tilesrcrect is null in entitiesldtk sample but...,in the entities example we there are some tile...,"[tilesrcrect, null, entitiesldtk, sample, null...","[entities, example, tilesrcrect, fields, null,..."
1,update the blog link in the sef site,describe the bug\r\nupdate the blog link in th...,"[update, blog, link, sef, site]","[describe, bug, update, blog, link, entire, we..."
2,🐛 parser cannot properly distinguish between p...,consider these two expressions\r\n\r\nf g x\r\...,"[🐛, parser, properly, distinguish, parenthesis...","[consider, two, expressions, f, g, x, f, g, x,..."
3,row added snackbar is not visible if the grid ...,description \r\nwhen grid has no height and ...,"[row, added, snackbar, visible, grid, small, h...","[description, grid, height, data, single, row,..."
4,crash tcpwriteonsocket crashes when flushing ...,\r\nthank you for reporting a crash in opensip...,"[crash, tcpwriteonsocket, crashes, flushing, a...","[thank, reporting, crash, opensips, order, us,..."

In [11]:
###Stemming

In [12]:
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()

def stemming(text):
    stem_text = [porter.stem(word) for word in text]
    return stem_text
text_data.loc[:,'token_title'] = text_data['token_title'].apply(lambda x:stemming(x))
text_data.loc[:,'token_body'] = text_data['token_body'].apply(lambda x:stemming(x))
text_data.head()

,issue_title,issue_body,token_title,token_body
0,tilesrcrect is null in entitiesldtk sample but...,in the entities example we there are some tile...,"[tilesrcrect, null, entitiesldtk, sampl, nulla...","[entiti, exampl, tilesrcrect, field, null, htt..."
1,update the blog link in the sef site,describe the bug\r\nupdate the blog link in th...,"[updat, blog, link, sef, site]","[describ, bug, updat, blog, link, entir, websi..."
2,🐛 parser cannot properly distinguish between p...,consider these two expressions\r\n\r\nf g x\r\...,"[🐛, parser, properli, distinguish, parenthesis...","[consid, two, express, f, g, x, f, g, x, first..."
3,row added snackbar is not visible if the grid ...,description \r\nwhen grid has no height and ...,"[row, ad, snackbar, visibl, grid, small, height]","[descript, grid, height, data, singl, row, ad,..."
4,crash tcpwriteonsocket crashes when flushing ...,\r\nthank you for reporting a crash in opensip...,"[crash, tcpwriteonsocket, crash, flush, async,...","[thank, report, crash, opensip, order, us, und..."

In [13]:
###Lemmatization

In [14]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemma = WordNetLemmatizer()

def lemmatization(text):
    tokens = [lemma.lemmatize(word) for word in text]
    return tokens

text_data.loc[:,'token_title'] = text_data['token_title'].apply(lambda x:lemmatization(x))
text_data.loc[:,'token_body'] = text_data['token_body'].apply(lambda x:lemmatization(x))
text_data.head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\imerp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,issue_title,issue_body,token_title,token_body
0,tilesrcrect is null in entitiesldtk sample but...,in the entities example we there are some tile...,"[tilesrcrect, null, entitiesldtk, sampl, nulla...","[entiti, exampl, tilesrcrect, field, null, htt..."
1,update the blog link in the sef site,describe the bug\r\nupdate the blog link in th...,"[updat, blog, link, sef, site]","[describ, bug, updat, blog, link, entir, websi..."
2,🐛 parser cannot properly distinguish between p...,consider these two expressions\r\n\r\nf g x\r\...,"[🐛, parser, properli, distinguish, parenthesis...","[consid, two, express, f, g, x, f, g, x, first..."
3,row added snackbar is not visible if the grid ...,description \r\nwhen grid has no height and ...,"[row, ad, snackbar, visibl, grid, small, height]","[descript, grid, height, data, singl, row, ad,..."
4,crash tcpwriteonsocket crashes when flushing ...,\r\nthank you for reporting a crash in opensip...,"[crash, tcpwriteonsocket, crash, flush, async,...","[thank, report, crash, opensip, order, u, unde..."